name: gbai_cuda_lm
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pip=24.0
  - pytorch::pytorch>=2.0
  - pip:
      - sentencepiece
      - huggingface-hub
      - transformers>=4.38.0
      - accelerate
      - colorama
      - datasets
      - lm-eval==0.3.0
      - termcolor
      - pillow
      - requests
      - prompt-toolkit
      - rich
      - optimum
      - auto-gptq
      - langchain-core
